# -*- coding: utf-8 -*-
"""Plant_Health_Monitoring_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KcsowQenBLHLrH5qB08zVu8cf6PizPwe
"""

# Import necessary libraries
import os
import cv2
import numpy as np
import pandas as pd

from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    StratifiedKFold
)

from sklearn.ensemble import (
    RandomForestClassifier,
    GradientBoostingClassifier
)

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder

from matplotlib import pyplot as plt
import seaborn as sns


# Function to define health categories based on NDVI values
def categorize_health(ndvi):
    if -1 <= ndvi < 0:
        return "Dead"
    elif 0 <= ndvi <= 0.33:
        return "Unhealthy"
    elif 0.33 < ndvi <= 0.66:
        return "Moderately Healthy"
    elif 0.66 < ndvi <= 1:
        return "Very Healthy"
    else:
        return "Unknown"


# Function to extract RGB color features from an image
def extract_image_features(image_path):

    if not os.path.exists(image_path):
        raise ValueError(
            f"File not found: {image_path}. Please check the file path."
        )

    image = cv2.imread(image_path)

    if image is None:
        raise ValueError(
            f"Cannot read the image from {image_path}. Please ensure it's a valid image."
        )

    image = cv2.resize(image, (128, 128))

    avg_color = np.mean(image, axis=(0, 1))

    return avg_color[::-1]  # Reverse BGR to RGB


# Function to update or create a dataset with new entries
def update_dataset(
    image_path,
    ndvi,
    plant_name,
    dataset_path="plant_health_dataset.csv"
):

    try:
        rgb_features = extract_image_features(image_path)

    except ValueError as e:
        print(e)
        return None

    health_category = categorize_health(ndvi)

    data = {
        "Plant Name": plant_name,
        "R": rgb_features[0],
        "G": rgb_features[1],
        "B": rgb_features[2],
        "NDVI": ndvi,
        "Health": health_category,
    }

    if os.path.exists(dataset_path):

        df = pd.read_csv(dataset_path)

        new_row_df = pd.DataFrame([data])

        df = pd.concat(
            [df, new_row_df],
            ignore_index=True
        )

    else:
        df = pd.DataFrame([data])

    df.to_csv(dataset_path, index=False)

    print("Dataset updated successfully!")

    return df


# Function to load an existing dataset
def load_dataset(
    dataset_path="plant_health_dataset.csv"
):

    if not os.path.exists(dataset_path):
        print("Dataset not found! Please create it first.")
        return None

    df = pd.read_csv(dataset_path)

    print(f"Loaded dataset with {len(df)} entries.")

    return df


# Encode the 'Health' column for machine learning purposes
def encode_health_column(df):

    encoder = LabelEncoder()

    df["Health"] = encoder.fit_transform(
        df["Health"]
    )

    return df


# Perform exploratory data analysis (EDA) on the dataset
def exploratory_data_analysis(
    dataset_path="plant_health_dataset.csv"
):

    df = load_dataset(dataset_path)

    if df is None:
        return

    df = encode_health_column(df)

    print("\n--- Data Summary ---")
    print(df.describe())

    print("\n--- Unique Values ---")
    print(df.nunique())

    print("\n--- Missing Values ---")
    print(df.isnull().sum())

    print("\n--- Health Category Counts ---")

    health_counts = df["Health"].value_counts()

    print(health_counts)

    numeric_columns = df.select_dtypes(
        include=["number"]
    )

    plt.figure(figsize=(8, 6))

    sns.heatmap(
        numeric_columns.corr(),
        annot=True,
        cmap="coolwarm",
        fmt=".2f"
    )

    plt.title("Correlation Heatmap")
    plt.show()

    plt.figure(figsize=(8, 6))

    sns.histplot(
        df["NDVI"],
        kde=True,
        bins=20,
        color="skyblue"
    )

    plt.title("NDVI Distribution")
    plt.xlabel("NDVI")
    plt.ylabel("Frequency")

    plt.show()

    plt.figure(figsize=(12, 6))

    for i, color in enumerate(
        ["R", "G", "B"], 1
    ):

        plt.subplot(1, 3, i)

        sns.histplot(
            df[color],
            kde=True,
            bins=20,
            color=color.lower()
        )

        plt.title(
            f"{color} Distribution"
        )

        plt.xlabel(
            f"{color} Intensity"
        )

        plt.ylabel("Frequency")

    plt.tight_layout()

    plt.show()

    plt.figure(figsize=(8, 6))

    sns.countplot(
        data=df,
        x="Health",
        palette="Set3"
    )

    plt.title(
        "Health Category Distribution"
    )

    plt.ylabel("Count")
    plt.xlabel("Health Category")

    plt.xticks(rotation=45)

    plt.show()
    # Function to count health categories and visualize with a pie chart
def count_health_categories(
    dataset_path="plant_health_dataset.csv"
):

    df = load_dataset(dataset_path)

    if df is None:
        return

    print("\n--- Health Category Counts ---")

    health_counts = df["Health"].value_counts()

    for category, count in health_counts.items():
        print(f"{category}: {count}")

    plt.figure(figsize=(8, 8))

    health_labels = health_counts.index
    health_values = health_counts.values

    plt.pie(
        health_values,
        labels=health_labels,
        autopct="%1.1f%%",
        startangle=140,
        colors=["green", "orange", "yellow", "red"]
    )

    plt.title("Health Category Distribution")

    plt.show()


# Recommend treatment for unhealthy plants
def recommend_treatment_for_unhealthy(ndvi):

    health_category = categorize_health(ndvi)

    if health_category != "Unhealthy":
        return (
            "This plant is not categorized as unhealthy. "
            "No treatment needed."
        )

    treatments = [
        "Increase watering frequency but avoid overwatering.",
        "Apply organic fertilizer to replenish nutrients in the soil.",
        "Inspect for pests or diseases and apply appropriate remedies.",
        "Ensure the plant gets adequate sunlight and ventilation.",
        "Prune damaged leaves and stems to promote healthy growth.",
        "Check soil pH and amend if necessary for optimal growth.",
    ]

    return (
        health_category,
        np.random.choice(treatments)
    )


# Predict health category using NDVI
def predict_health_from_ndvi(
    ndvi,
    dataset_path="plant_health_dataset.csv"
):

    df = load_dataset(dataset_path)

    if df is None:
        return

    df["NDVI_diff"] = abs(
        df["NDVI"] - ndvi
    )

    closest_match = df.loc[
        df["NDVI_diff"].idxmin()
    ]

    health_category = closest_match["Health"]

    print(
        f"Closest NDVI value in the dataset: "
        f"{closest_match['NDVI']}"
    )

    print(
        f"Predicted Health Category: "
        f"{health_category}"
    )


# Train machine learning models
def train_models(
    dataset_path="plant_health_dataset.csv"
):

    df = load_dataset(dataset_path)

    if df is None:
        return

    df = encode_health_column(df)

    X = df[["R", "G", "B", "NDVI"]]
    y = df["Health"]

    # Warning for small dataset
    if len(df) < 10:
        print(
            "Warning: Dataset is very small. "
            "Results may not generalize well."
        )

    if y.nunique() < 2:
        print(
            "Warning: Dataset has fewer than two classes. "
            "Model training may not be meaningful."
        )
        return

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42
    )

    models = {
        "Support Vector Classifier": SVC(),
        "Gradient Boosting Classifier": GradientBoostingClassifier(),
        "Random Forest Classifier": RandomForestClassifier(),
    }

    for name, model in models.items():

        print(f"\nTraining {name}...")

        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)

        acc = accuracy_score(
            y_test,
            y_pred
        )

        print(
            f"{name} Accuracy: "
            f"{acc * 100:.2f}%"
        )

        print(
            classification_report(
                y_test,
                y_pred,
                zero_division=1
            )
        )

        # Dynamically determine folds
        min_class_size = min(
            y.value_counts()
        )

        cv_folds = min(
            5,
            min_class_size
        )

        if cv_folds < 2:

            print(
                f"Skipping cross-validation for {name}: "
                f"Not enough samples per class."
            )

        else:

            try:

                skf = StratifiedKFold(
                    n_splits=cv_folds,
                    shuffle=True,
                    random_state=42
                )

                scores = cross_val_score(
                    model,
                    X,
                    y,
                    cv=skf
                )

                print(
                    f"{name} Cross-Validation Accuracy: "
                    f"{np.mean(scores) * 100:.2f}%"
                )

            except ValueError as e:

                print(
                    f"Cross-validation failed for "
                    f"{name}: {e}"
                )


# Main menu loop
if __name__ == "__main__":

    print("Plant Health Monitoring System")

    while True:

        print("\nOptions:")
        print("1. Update Dataset")
        print("2. Train Models")
        print("3. Perform EDA")
        print("4. Predict Health from NDVI")
        print("5. Display Health Category Counts")
        print("6. Recommend Treatment for Unhealthy Plants")
        print("7. Quit")

        choice = input(
            "Enter your choice (1-7): "
        ).strip()

        if choice == "1":

            image_path = input(
                "Enter the path to the image: "
            ).strip()

            plant_name = input(
                "Enter the plant name: "
            ).strip()

            try:

                ndvi = float(
                    input(
                        "Enter the NDVI value (-1 to 1): "
                    )
                )

                update_dataset(
                    image_path,
                    ndvi,
                    plant_name
                )

            except ValueError:

                print(
                    "Invalid NDVI value. "
                    "Please enter a number between -1 and 1."
                )

        elif choice == "2":

            train_models()

        elif choice == "3":

            exploratory_data_analysis()

        elif choice == "4":

            try:

                ndvi_input = float(
                    input(
                        "Enter the NDVI value (-1 to 1): "
                    )
                )

                predict_health_from_ndvi(
                    ndvi_input
                )

            except ValueError:

                print(
                    "Invalid NDVI value."
                )

        elif choice == "5":

            count_health_categories()

        elif choice == "6":

            try:

                ndvi_input = float(
                    input(
                        "Enter the NDVI value (-1 to 1): "
                    )
                )

                result = recommend_treatment_for_unhealthy(
                    ndvi_input
                )

                if isinstance(result, tuple):

                    health_category, treatment = result

                    print(
                        f"Health Category: "
                        f"{health_category}"
                    )

                    print(
                        f"Recommended Treatment: "
                        f"{treatment}"
                    )

                else:

                    print(result)

            except ValueError:

                print(
                    "Invalid NDVI value. "
                    "Please enter a number between -1 and 1."
                )

        elif choice == "7":

            print(
                "Exiting the Plant Health Monitoring System. Goodbye!"
            )

            break

        else:

            print(
                "Invalid choice. Please select a valid option (1-7)."
            )